# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0jSParFIH5wqaNdrF-dt7A0Kv6M4Yg4
"""

# XÂY DỰNG VÀ HUẤN LUYỆN MÔ HÌNH 1D-CNN AUTOENCODER HYBRID
l2_reg = regularizers.l2(1e-5)

# --- 1. Nhánh Encoder (Trích xuất đặc trưng từ FFT 5 kênh) ---
input_fft = layers.Input(shape=(512, 5), name="input_fft")

x = layers.Conv1D(64, kernel_size=5, padding='same', activation='relu', kernel_regularizer=l2_reg)(input_fft)
x = layers.LayerNormalization()(x)
x = layers.MaxPooling1D(2)(x)
x = layers.SpatialDropout1D(0.15)(x)

x = layers.Conv1D(128, kernel_size=5, padding='same', activation='relu', dilation_rate=2, kernel_regularizer=l2_reg)(x)
x = layers.LayerNormalization()(x)
x = layers.MaxPooling1D(2)(x)
x = layers.SpatialDropout1D(0.15)(x)

x = layers.Conv1D(256, kernel_size=3, padding='same', activation='relu', dilation_rate=4, kernel_regularizer=l2_reg)(x)
x = layers.LayerNormalization()(x)
x = layers.MaxPooling1D(2)(x)
x = layers.SpatialDropout1D(0.15)(x)

bottleneck = layers.GlobalAveragePooling1D(name="latent_bottleneck")(x)

# --- 2. Nhánh Decoder (Dùng trong quá trình train để học không giám sát) ---
d = layers.Reshape((1, 256))(bottleneck)
d = layers.UpSampling1D(64)(d)
d = layers.Conv1D(128, kernel_size=3, padding='same', activation='relu')(d)
d = layers.UpSampling1D(2)(d)
d = layers.Conv1D(64, kernel_size=5, padding='same', activation='relu')(d)
d = layers.UpSampling1D(4)(d)
decoded_output = layers.Conv1D(5, kernel_size=3, padding='same', activation='linear', name="reconstruction")(d)

# --- 3. Nhánh Classifier Head (Kết hợp Bottleneck và Thống kê miền thời gian) ---
input_stats = layers.Input(shape=(12,), name="input_stats")
combined_features = layers.Concatenate(name="concat_latent_stats")([bottleneck, input_stats])

c = layers.Dense(128, activation='relu', kernel_regularizer=l2_reg)(combined_features)
c = layers.LayerNormalization()(c)
c = layers.Dropout(0.3)(c)

c = layers.Dense(64, activation='relu', kernel_regularizer=l2_reg)(c)
c = layers.LayerNormalization()(c)
c = layers.Dropout(0.2)(c)

classifier_output = layers.Dense(4, activation='softmax', name="classification")(c)

# --- 4. Khởi tạo và Biên dịch Joint Model (Multi-task Learning) ---
joint_model = models.Model(
    inputs=[input_fft, input_stats],
    outputs=[decoded_output, classifier_output],
    name="Training_Joint_Model"
)

joint_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss={"reconstruction": "mse", "classification": "categorical_crossentropy"},
    loss_weights={"reconstruction": 0.005, "classification": 1.0},
    metrics={"classification": "accuracy"}
)

# --- 5. Cấu hình Callbacks và Quá trình Huấn luyện (Fit) ---
callbacks_list = [
    tf.keras.callbacks.EarlyStopping(monitor='val_classification_accuracy', patience=20, restore_best_weights=True, mode='max'),
    tf.keras.callbacks.ReduceLROnPlateau(monitor='val_classification_loss', factor=0.5, patience=4, min_lr=1e-6, mode='min', verbose=1)
]

history = joint_model.fit(
    {"input_fft": X_fft_train_comb, "input_stats": X_stats_train_comb},
    {"reconstruction": X_fft_train_comb, "classification": y_train_comb},
    validation_data=(
        {"input_fft": X_fft_val, "input_stats": X_stats_val},
        {"reconstruction": X_fft_val, "classification": y_val}
    ),
    epochs=60,
    batch_size=128,
    callbacks=callbacks_list
)